# Generated by Django 5.0.1 on 2024-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='c381739b4f9e4796', max_length=32, unique=True),
        ),
    ]
