# Generated by Django 5.0.1 on 2024-07-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_ride_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ambulance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='192a3ffaf33b47d7', max_length=32, unique=True),
        ),
    ]
