# Generated by Django 5.0.1 on 2024-08-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_ride_ambulance_type_alter_ride_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='fa481e5d9b4846df', max_length=32, unique=True),
        ),
    ]
