# Generated by Django 5.0.1 on 2024-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_ride_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='2b5e0318b4ec4920', max_length=32, unique=True),
        ),
    ]
