# Generated by Django 5.0.1 on 2024-08-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_ride_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default='fecd9badfd9c4986', max_length=32, unique=True),
        ),
    ]
