# Generated by Django 5.0.1 on 2026-05-30 14:01

import map.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_hospital_ride_is_completed_ride_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_completed',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='is_verified',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='token',
            field=models.CharField(default=map.models.generate_token, max_length=32, unique=True),
        ),
    ]
