# Generated by Django 5.0.1 on 2026-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_driverlocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_type', models.CharField(help_text='e.g. med_bls, med_als, med_icu', max_length=50, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
    ]
