# Generated by Django 5.0.1 on 2024-07-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='ambulance_type',
            field=models.CharField(choices=[('medbasic', 'MedBasic'), ('medpro', 'MedPro')], max_length=10),
        ),
    ]
