# Generated by Django 5.0.1 on 2024-08-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_alter_driver_ambulance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to='verify.customuser'),
        ),
    ]
