# Generated by Django 5.0.1 on 2024-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0003_alter_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ambulance_type',
            field=models.CharField(blank=True, choices=[('med_bls', 'Med BLS'), ('med_als', 'Med ALS'), ('med_icu', 'Med ICU')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='number_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
