# Generated by Django 5.0.1 on 2026-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0004_driver_car_name_driver_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
